# Generated by Django 4.1.3 on 2023-11-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='user_default.webp', upload_to='avatar/')),
                ('cover', models.ImageField(blank=True, default='cover_default.png', upload_to='cover/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('phone', models.IntegerField(blank=True, default=False)),
                ('gander', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_publesher', models.BooleanField(blank=True, default=False)),
                ('is_blocked', models.BooleanField(blank=True, default=False)),
                ('birth', models.CharField(blank=True, max_length=300)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('verificated', models.BooleanField(default=False)),
                ('trafiq', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('flag', models.CharField(blank=True, max_length=2000)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('continent', models.CharField(blank=True, max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('earning', models.FloatField(default=0.0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('block', models.ManyToManyField(blank=True, related_name='user_block', to=settings.AUTH_USER_MODEL)),
                ('follow', models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewrs', models.ManyToManyField(blank=True, related_name='user_viewrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
