# Generated by Django 4.1.3 on 2023-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cover_description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cover_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
