# Generated by Django 4.1.3 on 2023-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_settings_cover_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='Favicons'),
        ),
        migrations.AddField(
            model_name='settings',
            name='theme_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
