# Generated by Django 4.1.3 on 2022-11-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_contact_page_post_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tages',
            new_name='tags',
        ),
    ]
