# Generated by Django 4.1.3 on 2023-11-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_settings_footer_settings_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='footer',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='header',
            new_name='script',
        ),
    ]
