# Generated by Django 4.1.3 on 2022-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_rename_tages_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
