# Generated by Django 4.1.3 on 2023-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_rename_footer_settings_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ads',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ads file (ads.txt)'),
        ),
    ]
