# Generated by Django 4.1.3 on 2023-11-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_post_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_link',
        ),
        migrations.AddField(
            model_name='contact',
            name='readed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
