# Generated by Django 4.1.3 on 2023-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_remove_post_image_link_contact_readed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('footer', models.BooleanField(blank=True, null=True)),
                ('header', models.BooleanField(blank=True, null=True)),
                ('new_tab', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=400)),
                ('tags', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='Logos')),
                ('cover', models.ImageField(upload_to='Covers')),
                ('cover_title', models.CharField(max_length=100)),
                ('cover_description', models.CharField(max_length=150)),
            ],
        ),
    ]
