# Generated by Django 4.1.3 on 2023-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_link_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cover_description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(),
        ),
    ]
